Repository DDD-Community/jsonWeb-server, pull requests merged in 2022-12, with the labels that each got.

#12 Feature/5
  build.gradle.kts
  src/main/kotlin/jsonweb/exitserver/common/CommonResponse.kt
  src/main/kotlin/jsonweb/exitserver/s3/S3Config.kt
  src/main/kotlin/jsonweb/exitserver/s3/S3Controller.kt
  src/main/kotlin/jsonweb/exitserver/s3/S3Service.kt
  src/main/kotlin/jsonweb/exitserver/s3/S3TypeDir.kt
  src/main/kotlin/jsonweb/exitserver/s3/UploadImageRequest.kt
  src/main/kotlin/jsonweb/exitserver/s3/UploadImageResponse.kt
  src/main/resources/application.yml
Labels: 리뷰 완료

#16 Feature/3
  build.gradle.kts
  src/main/kotlin/jsonweb/exitserver/Test.kt
  src/main/kotlin/jsonweb/exitserver/TestController.kt
  src/main/kotlin/jsonweb/exitserver/TestRepository.kt
  src/main/kotlin/jsonweb/exitserver/auth/KakaoClient.kt
  src/main/kotlin/jsonweb/exitserver/auth/jwt/JwtFilter.kt
  src/main/kotlin/jsonweb/exitserver/auth/jwt/JwtProvider.kt
  src/main/kotlin/jsonweb/exitserver/auth/security/PrincipalDetails.kt
  src/main/kotlin/jsonweb/exitserver/auth/security/SecurityConfig.kt
  src/main/kotlin/jsonweb/exitserver/common/CustomExceptions.kt
  src/main/kotlin/jsonweb/exitserver/domain/user/User.kt
  src/main/kotlin/jsonweb/exitserver/domain/user/UserController.kt
  src/main/kotlin/jsonweb/exitserver/domain/user/UserDto.kt
  src/main/kotlin/jsonweb/exitserver/domain/user/UserRepository.kt
  src/main/kotlin/jsonweb/exitserver/domain/user/UserService.kt
  src/main/kotlin/jsonweb/exitserver/s3/S3Config.kt
  src/main/kotlin/jsonweb/exitserver/s3/S3TypeDir.kt
  src/main/kotlin/jsonweb/exitserver/s3/UploadImageRequest.kt
  src/main/kotlin/jsonweb/exitserver/s3/UploadImageResponse.kt
  src/main/kotlin/jsonweb/exitserver/security/SecurityConfig.kt
  src/main/kotlin/jsonweb/exitserver/swagger/SwaggerConfig.kt
  src/main/kotlin/jsonweb/exitserver/util/NicknameGenerator.kt
  src/main/kotlin/jsonweb/exitserver/util/s3/S3Config.kt
  src/main/kotlin/jsonweb/exitserver/util/s3/S3Controller.kt
  src/main/kotlin/jsonweb/exitserver/util/s3/S3Dto.kt
  src/main/kotlin/jsonweb/exitserver/util/s3/S3Service.kt
  src/main/kotlin/jsonweb/exitserver/util/swagger/SwaggerConfig.kt
  src/main/kotlin/jsonweb/exitserver/util/swagger/SwaggerRedirector.kt
Labels: 기능, 리뷰 대기 중

#26 feature/23: 회원 API 추가 기능 구현
  src/main/kotlin/jsonweb/exitserver/auth/KakaoClient.kt
  src/main/kotlin/jsonweb/exitserver/auth/jwt/JwtProvider.kt
  src/main/kotlin/jsonweb/exitserver/auth/security/SecurityConfig.kt
  src/main/kotlin/jsonweb/exitserver/domain/user/User.kt
  src/main/kotlin/jsonweb/exitserver/domain/user/UserController.kt
  src/main/kotlin/jsonweb/exitserver/domain/user/UserRepository.kt
  src/main/kotlin/jsonweb/exitserver/domain/user/UserService.kt
  src/test/kotlin/jsonweb/exitserver/domain/UserServiceTest.kt
Labels: 주요 기능

#27 feature/25: 카페API 추가 기능 및 기존 기능 수정
  build.gradle.kts
  src/main/kotlin/jsonweb/exitserver/domain/cafe/Cafe.kt
  src/main/kotlin/jsonweb/exitserver/domain/cafe/CafeController.kt
  src/main/kotlin/jsonweb/exitserver/domain/cafe/CafeDto.kt
  src/main/kotlin/jsonweb/exitserver/domain/cafe/CafeKeywordRepository.kt
  src/main/kotlin/jsonweb/exitserver/domain/cafe/CafeLikeRepository.kt
  src/main/kotlin/jsonweb/exitserver/domain/cafe/CafeReportRepository.kt
  src/main/kotlin/jsonweb/exitserver/domain/cafe/CafeRepository.kt
  src/main/kotlin/jsonweb/exitserver/domain/cafe/CafeRepositoryImpl.kt
  src/main/kotlin/jsonweb/exitserver/domain/cafe/CafeService.kt
  src/main/kotlin/jsonweb/exitserver/util/QueryDslConfig.kt
  src/main/kotlin/jsonweb/exitserver/util/TestConfig.kt
  src/test/kotlin/jsonweb/exitserver/domain/cafe/CafeLikeRepositoryTest.kt
  src/test/kotlin/jsonweb/exitserver/domain/cafe/CafeRepositoryImplTest.kt
  src/test/kotlin/jsonweb/exitserver/domain/cafe/CafeRepositoryTest.kt
  src/test/kotlin/jsonweb/exitserver/domain/cafe/CafeServiceTest.kt
Labels: 주요 기능

#35 feature/32: 마이페이지 카페 문의 API 제작
  src/main/kotlin/jsonweb/exitserver/auth/jwt/JwtFilter.kt
  src/main/kotlin/jsonweb/exitserver/auth/jwt/JwtHandlers.kt
  src/main/kotlin/jsonweb/exitserver/auth/security/SecurityConfig.kt
  src/main/kotlin/jsonweb/exitserver/common/BaseTimeEntity.kt
  src/main/kotlin/jsonweb/exitserver/common/CustomExceptions.kt
  src/main/kotlin/jsonweb/exitserver/config/ModelMapperConfig.kt
  src/main/kotlin/jsonweb/exitserver/config/QueryDslConfig.kt
  src/main/kotlin/jsonweb/exitserver/config/TestConfig.kt
  src/main/kotlin/jsonweb/exitserver/config/WebConfig.kt
  src/main/kotlin/jsonweb/exitserver/domain/cafe/Cafe.kt
  src/main/kotlin/jsonweb/exitserver/domain/cafe/CafeDto.kt
  src/main/kotlin/jsonweb/exitserver/domain/cafe/CafeKeywordRepository.kt
  src/main/kotlin/jsonweb/exitserver/domain/cafe/CafeLikeRepository.kt
  src/main/kotlin/jsonweb/exitserver/domain/cafe/CafeReportRepository.kt
  src/main/kotlin/jsonweb/exitserver/domain/cafe/CafeRepository.kt
  src/main/kotlin/jsonweb/exitserver/domain/cafe/CafeRepositoryImpl.kt
  src/main/kotlin/jsonweb/exitserver/domain/cafe/CafeService.kt
  src/main/kotlin/jsonweb/exitserver/domain/inquiry/Inquiry.kt
  src/main/kotlin/jsonweb/exitserver/domain/inquiry/InquiryController.kt
  src/main/kotlin/jsonweb/exitserver/domain/inquiry/InquiryDto.kt
  src/main/kotlin/jsonweb/exitserver/domain/inquiry/InquiryRepository.kt
  src/main/kotlin/jsonweb/exitserver/domain/inquiry/InquiryService.kt
  src/main/kotlin/jsonweb/exitserver/domain/theme/GenreRepository.kt
  src/main/kotlin/jsonweb/exitserver/domain/theme/Theme.kt
  src/main/kotlin/jsonweb/exitserver/domain/theme/ThemeDto.kt
  src/main/kotlin/jsonweb/exitserver/domain/theme/ThemeGenreRepository.kt
  src/main/kotlin/jsonweb/exitserver/domain/theme/ThemeRepository.kt
  src/main/kotlin/jsonweb/exitserver/domain/theme/ThemeService.kt
  src/main/kotlin/jsonweb/exitserver/domain/user/User.kt
  src/main/kotlin/jsonweb/exitserver/domain/user/UserService.kt
  src/main/kotlin/jsonweb/exitserver/util/DataGenerator.kt
  src/main/resources/application.yml
  src/test/kotlin/jsonweb/exitserver/domain/cafe/CafeLikeRepositoryTest.kt
  src/test/kotlin/jsonweb/exitserver/domain/cafe/CafeRepositoryImplTest.kt
  src/test/kotlin/jsonweb/exitserver/domain/cafe/CafeRepositoryTest.kt
  src/test/kotlin/jsonweb/exitserver/domain/cafe/CafeServiceTest.kt
  src/test/kotlin/jsonweb/exitserver/domain/inquiry/InquiryServiceTest.kt
  src/test/kotlin/jsonweb/exitserver/domain/theme/ThemeServiceTest.kt
  src/test/kotlin/jsonweb/exitserver/domain/user/UserServiceTest.kt
Labels: 서브 기능

#37 feature/21 인증 게시판 API 제작
  src/main/kotlin/jsonweb/exitserver/auth/jwt/JwtProvider.kt
  src/main/kotlin/jsonweb/exitserver/auth/security/PrincipalDetails.kt
  src/main/kotlin/jsonweb/exitserver/auth/security/SecurityConfig.kt
  src/main/kotlin/jsonweb/exitserver/common/GlobalConst.kt
  src/main/kotlin/jsonweb/exitserver/domain/boast/Boast.kt
  src/main/kotlin/jsonweb/exitserver/domain/boast/BoastController.kt
  src/main/kotlin/jsonweb/exitserver/domain/boast/BoastDto.kt
  src/main/kotlin/jsonweb/exitserver/domain/boast/BoastRepository.kt
  src/main/kotlin/jsonweb/exitserver/domain/boast/BoastService.kt
  src/main/kotlin/jsonweb/exitserver/domain/cafe/Cafe.kt
  src/main/kotlin/jsonweb/exitserver/domain/cafe/CafeController.kt
  src/main/kotlin/jsonweb/exitserver/domain/cafe/CafeService.kt
  src/main/kotlin/jsonweb/exitserver/domain/inquiry/Inquiry.kt
  src/main/kotlin/jsonweb/exitserver/domain/inquiry/InquiryController.kt
  src/main/kotlin/jsonweb/exitserver/domain/inquiry/InquiryDto.kt
  src/main/kotlin/jsonweb/exitserver/domain/inquiry/InquiryService.kt
  src/main/kotlin/jsonweb/exitserver/domain/review/ReviewController.kt
  src/main/kotlin/jsonweb/exitserver/domain/review/ReviewService.kt
  src/main/kotlin/jsonweb/exitserver/domain/theme/Theme.kt
  src/main/kotlin/jsonweb/exitserver/domain/theme/ThemeController.kt
  src/main/kotlin/jsonweb/exitserver/domain/user/User.kt
  src/main/kotlin/jsonweb/exitserver/domain/user/UserController.kt
  src/main/kotlin/jsonweb/exitserver/domain/user/UserService.kt
  src/main/kotlin/jsonweb/exitserver/util/DataGenerator.kt
  src/main/resources/application.yml
  src/test/kotlin/jsonweb/exitserver/domain/boast/BoastServiceTest.kt
  src/test/kotlin/jsonweb/exitserver/domain/inquiry/InquiryServiceTest.kt
  src/test/kotlin/jsonweb/exitserver/domain/theme/ThemeServiceTest.kt
Labels: 주요 기능

#36 feature/33: 카페,테마,리뷰 API 보완
  src/main/kotlin/jsonweb/exitserver/domain/cafe/Cafe.kt
  src/main/kotlin/jsonweb/exitserver/domain/cafe/CafeController.kt
  src/main/kotlin/jsonweb/exitserver/domain/cafe/CafeDto.kt
  src/main/kotlin/jsonweb/exitserver/domain/cafe/CafeRepository.kt
  src/main/kotlin/jsonweb/exitserver/domain/cafe/CafeService.kt
  src/main/kotlin/jsonweb/exitserver/domain/review/ReviewController.kt
  src/main/kotlin/jsonweb/exitserver/domain/review/ReviewDto.kt
  src/main/kotlin/jsonweb/exitserver/domain/review/ReviewService.kt
  src/main/kotlin/jsonweb/exitserver/domain/theme/Theme.kt
  src/main/kotlin/jsonweb/exitserver/domain/theme/ThemeController.kt
  src/main/kotlin/jsonweb/exitserver/domain/theme/ThemeDto.kt
  src/main/kotlin/jsonweb/exitserver/domain/theme/ThemeService.kt
  src/test/kotlin/jsonweb/exitserver/domain/cafe/CafeRepositoryImplTest.kt
Labels: 서브 기능

#40 feature/38 공통, 회원, 인증, 문의 API 엔드포인트 변경
  src/main/kotlin/jsonweb/exitserver/domain/user/UserController.kt
  src/main/kotlin/jsonweb/exitserver/util/s3/S3Controller.kt
  src/main/kotlin/jsonweb/exitserver/util/s3/S3Dto.kt
  src/main/kotlin/jsonweb/exitserver/util/s3/S3Service.kt
Labels: 리펙토링

#42 feature/41 유저 등급 추가
  src/main/kotlin/jsonweb/exitserver/domain/user/User.kt
Labels: 서브 기능
